#!/usr/bin/env python
"""The rules that used to end a report with "go and log into the switch".

Run directly: `python3 tests/test_manual_review_rules.py`. No framework, no
device. Driven through the CLI like the other audit suites - l2_stig_audit.py
parses argv at import, so a report is the only way to read its verdicts.

Every case here came off one hand-annotated IOS XE report:

  * V-220531/532/533 (persistent logging) reported PASS with a reason that
    said the rule was not applicable. Two different sentences on a checklist,
    and only one of them is true - `NOT_A_FINDING` claims the switch protects
    persistent log files it does not keep.

  * V-220567 (PKI) reported NOT AUTOMATED on every switch, because every
    switch has a trustpoint: `TP-self-signed-<serial>`, generated by IOS XE
    itself. Nothing there enrolled with a CA, so the review the rule asks for
    has no subject - confirmed on a real switch with `show running-config |
    include enrollment url`, which printed nothing. Where a switch IS enrolled,
    the URL that names the CA is in running-config too, and comparing its host
    against the approved list is the rule's whole review step - so that is
    answered here rather than handed back.

  * V-220569 (supported release) was NOT AUTOMATED with nothing to act on. It
    needs `show version`, which the audit is already connected to run.

  * V-220651 (QoS) was NOT AUTOMATED because the IOS book's `mls qos` cannot
    answer it. The IOS XE book asks for the MQC shape, which is config text.

V-220566 (configuration backups) stays NOT AUTOMATED: which server a switch
backs up to is a fact about the site, not about the switch, and no command
here can discover it.
"""

import os
import re
import subprocess
import sys
import tempfile

PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import capture
import fixtures

failures = []


def check(name, condition, detail=''):
    print(f'  {"ok  " if condition else "FAIL"} {name}')
    if not condition:
        if detail:
            print(f'       {detail}')
        failures.append(name)


def report_for(tmpdir, name, **overrides):
    """An IOS XE report for the fixture switch, with `show ...` outputs
    replaced by keyword: report_for(tmp, 'x', running_config=..., version=...)."""
    outputs = dict(fixtures.OUTPUTS)
    for key, command in (('running_config', 'show running-config'),
                         ('version', 'show version')):
        if key in overrides:
            outputs[command] = overrides[key]
    path = capture.write(os.path.join(tmpdir, name + '.capture'), outputs)
    result = subprocess.run(
        [sys.executable, os.path.join(PROJECT, 'l2_stig_audit.py'), 'TESTSW01',
         '--from-capture', path, '--non-user-vlans', '1,10,999,1000'],
        capture_output=True, text=True, cwd=PROJECT, timeout=120)
    return result.stdout + result.stderr


def verdict(report, rule_id):
    """The status line and its reason for one rule, as one string."""
    lines = report.splitlines()
    for i, line in enumerate(lines):
        if rule_id in line:
            return ' | '.join(part.strip() for part in lines[i:i + 2])
    return f'{rule_id} not in report'


def status(report, rule_id):
    line = verdict(report, rule_id).split('|')[0]
    for name in ('NOT APPLICABLE', 'NOT AUTOMATED', 'PASS', 'FAIL'):
        if name in line:
            return name
    return line.strip()


PERSISTENT = 'logging persistent url disk0:/logfile size 134217728 filesize 16384'
AUDIT_RULES = ('V-220531', 'V-220532', 'V-220533')


def test_persistent_logging(tmpdir):
    print('persistent logging: not enabled is not applicable, not a pass')
    off = report_for(tmpdir, 'nopersist')
    for rule in AUDIT_RULES:
        check(f'{rule} is NOT APPLICABLE with no `logging persistent`',
              status(off, rule) == 'NOT APPLICABLE', verdict(off, rule))

    on = report_for(tmpdir, 'persist', running_config=fixtures.RUNNING_CONFIG.replace(
        'logging buffered 64000', f'logging buffered 64000\n{PERSISTENT}'))
    for rule in AUDIT_RULES:
        check(f'{rule} passes once persistent logging is on and privilege is default 15',
              status(on, rule) == 'PASS', verdict(on, rule))
    check('and the reason says why an absent `file privilege` line is compliant',
          'default of privilege 15' in verdict(on, 'V-220531'), verdict(on, 'V-220531'))

    lowered = report_for(tmpdir, 'privilege10', running_config=fixtures.RUNNING_CONFIG.replace(
        'logging buffered 64000', f'logging buffered 64000\n{PERSISTENT}\nfile privilege 10'))
    for rule in AUDIT_RULES:
        check(f'{rule} fails on `file privilege 10`, which is the rule\'s finding',
              status(lowered, rule) == 'FAIL', verdict(lowered, rule))


def test_pki_trustpoint(tmpdir):
    print('\nPKI: a self-signed trustpoint is not a certificate from a provider')
    self_signed = report_for(tmpdir, 'selfsigned')
    check('V-220567 is NOT APPLICABLE against `TP-self-signed-...`',
          status(self_signed, 'V-220567') == 'NOT APPLICABLE', verdict(self_signed, 'V-220567'))
    check('and the reason names the trustpoint it decided that on',
          'TP-self-signed-1234567890' in verdict(self_signed, 'V-220567'),
          verdict(self_signed, 'V-220567'))

    none = report_for(tmpdir, 'notrustpoint', running_config=re.sub(
        r'crypto pki trustpoint.*?(?=banner login)', '', fixtures.RUNNING_CONFIG, flags=re.S))
    check('so is a switch with no trustpoint at all',
          status(none, 'V-220567') == 'NOT APPLICABLE', verdict(none, 'V-220567'))

    # The rule's own Check Content is "the CA trust point will contain the URL
    # of the CA ... verify this is a DOD or DOD-approved CA", and that URL is
    # in running-config - so the audit answers it rather than printing the URL
    # and asking someone to log in and read what it just read.
    enrolled = report_for(tmpdir, 'enrolled', running_config=fixtures.RUNNING_CONFIG.replace(
        ' enrollment selfsigned', ' enrollment url http://ca.example.mil'))
    check('a trustpoint enrolled with an approved CA passes',
          status(enrolled, 'V-220567') == 'PASS', verdict(enrolled, 'V-220567'))
    check('and the reason names the URL it decided that on',
          'http://ca.example.mil' in verdict(enrolled, 'V-220567'),
          verdict(enrolled, 'V-220567'))

    outside = report_for(tmpdir, 'unapprovedca', running_config=fixtures.RUNNING_CONFIG.replace(
        ' enrollment selfsigned', ' enrollment url http://ca.example.com'))
    check('a CA outside approved_ca_hosts is the finding, not a note',
          status(outside, 'V-220567') == 'FAIL', verdict(outside, 'V-220567'))
    check('and the reason says which host and which list',
          'ca.example.com' in verdict(outside, 'V-220567')
          and 'approved_ca_hosts' in verdict(outside, 'V-220567'),
          verdict(outside, 'V-220567'))

    # `enrollment terminal` is a real CA enrolment whose CA running-config
    # never names. That one stays NOT AUTOMATED - the honest verdict when the
    # evidence is not in the text - rather than being guessed either way.
    terminal = report_for(tmpdir, 'terminalenrol', running_config=fixtures.RUNNING_CONFIG.replace(
        ' enrollment selfsigned', ' enrollment terminal'))
    check('an enrolment with no URL in the config is still NOT AUTOMATED',
          status(terminal, 'V-220567') == 'NOT AUTOMATED', verdict(terminal, 'V-220567'))
    check('and names the command that answers it',
          'show crypto pki certificates' in verdict(terminal, 'V-220567'),
          verdict(terminal, 'V-220567'))


SHOW_VERSION_3850 = """Cisco IOS Software, IOS-XE Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.12.4, RELEASE SOFTWARE (fc5)
Technical Support: http://www.cisco.com/techsupport

cisco WS-C3850-48P (MIPS) processor with 862968K/6147K bytes of memory.

Model Number                         : WS-C3850-48P
System Serial Number                 : FOC0000X0XX"""

SHOW_VERSION_UNKNOWN_RELEASE = fixtures.SHOW_VERSION.replace('17.12.04', '17.15.01').replace(
    'Version 17.12.4', 'Version 17.15.1')

# Classic IOS prints neither of the two lines IOS XE does, and has no 'Model
# Number' line at all - the lab's own switches are this shape.
SHOW_VERSION_VIOS = """Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Experimental Version 15.2(20170717:130322) [dstivers-Bld_pi24 102]
Copyright (c) 1986-2017 by Cisco Systems, Inc.

S1 uptime is 1 day, 2 hours
System image file is "flash0:/vios_l2-adventerprisek9-m"

cisco vios_l2 (MIPS) processor with 508841K bytes of memory."""


# No `Cisco IOS XE Software, Version` banner this recognises and no `Model
# Number` line - everything the rule needs is in the switch table alone.
SHOW_VERSION_TABLE_ONLY = """Cisco IOS Software [Dublin], Catalyst L3 Switch Software (CAT9K_IOSXE)
Copyright (c) 1986-2024 by Cisco Systems, Inc.

TESTSW01 uptime is 3 weeks, 2 days, 4 hours, 11 minutes

Base Ethernet MAC Address            : 00:1A:2B:3C:4D:5E

Switch Ports Model              SW Version        SW Image              Mode
------ ----- -----              ----------        ----------            ----
*    1 52    C9300-48P          17.12.04          CAT9K_IOSXE           INSTALL

Configuration register is 0x102"""

# A stack, with the active member second and marked `*`. Reading the first row
# would report a release the switch in charge is not running.
SHOW_VERSION_STACK = SHOW_VERSION_TABLE_ONLY.replace(
    '*    1 52    C9300-48P          17.12.04          CAT9K_IOSXE           INSTALL',
    '     1 52    C9300-48P          16.09.08          CAT9K_IOSXE           INSTALL\n'
    '*    2 52    C9300-48P          17.12.04          CAT9K_IOSXE           INSTALL')


def test_supported_release(tmpdir):
    print('\nsupported release: `show version` answers the model and the release')
    known = report_for(tmpdir, 'release')
    line = verdict(known, 'V-220569')
    check('the release and the model are in the report, so no login is needed for them',
          '17.12.4' in line and 'C9300-48P' in line, line)
    # PASS while SUPPORTED_RELEASES is current, NOT AUTOMATED once that reading
    # goes stale - never a bare NOT AUTOMATED with nothing to act on.
    check('a reviewed release passes, or says the list needs re-reading',
          status(known, 'V-220569') == 'PASS' or 'update SUPPORTED_RELEASES' in line, line)

    past_support = report_for(tmpdir, 'eos', version=SHOW_VERSION_3850)
    line = verdict(past_support, 'V-220569')
    check('hardware past its last date of support is a finding, whatever it runs',
          status(past_support, 'V-220569') == 'FAIL', line)
    check('and the reason gives the date rather than asserting it',
          '2025-10-31' in line, line)

    classic = report_for(tmpdir, 'vios', version=SHOW_VERSION_VIOS)
    line = verdict(classic, 'V-220569')
    check('classic IOS names its release and model on different lines, and both are read',
          '15.2(20170717:130322)' in line and 'vios_l2' in line, line)

    unknown = report_for(tmpdir, 'unknownrelease', version=SHOW_VERSION_UNKNOWN_RELEASE)
    line = verdict(unknown, 'V-220569')
    check('a release the table does not know is NOT AUTOMATED, not a finding',
          status(unknown, 'V-220569') == 'NOT AUTOMATED', line)
    check('and it says so in those words, with the release to look up',
          '17.15.1' in line and 'unknown, not unsupported' in line, line)

    # The switch table at the end of `show version` is the third place the
    # model and release appear, and on some images the only one. A switch whose
    # banner this does not recognise and which prints no `Model Number` line
    # used to report "could not read a model from `show version`" with the
    # model on screen in the SW Version table the whole time.
    table_only = report_for(tmpdir, 'tableonly', version=SHOW_VERSION_TABLE_ONLY)
    line = verdict(table_only, 'V-220569')
    check('the SW Version column answers the rule when nothing else does',
          '17.12.4' in line and 'C9300-48P' in line, line)
    check('and it is the same verdict the banner would have given',
          status(table_only, 'V-220569') == status(known, 'V-220569'), line)

    stacked = report_for(tmpdir, 'stacked', version=SHOW_VERSION_STACK)
    line = verdict(stacked, 'V-220569')
    check('a stack is read from its active member, not whichever row came first',
          '17.12.4' in line and '16.9.8' not in line, line)


def strip_service_policy(config, *ports):
    """The fixture config with `service-policy output` removed from `ports`,
    or from every port if none are named."""
    out, current = [], None
    for line in config.splitlines():
        interface = re.match(r'interface (\S+)', line)
        if interface:
            current = interface.group(1)
        if 'service-policy output' in line and (not ports or current in ports):
            continue
        out.append(line)
    return '\n'.join(out)


def test_qos_bandwidth(tmpdir):
    print('\nQoS: the MQC shape the IOS XE book asks for, read from config text')
    compliant = report_for(tmpdir, 'qos')
    line = verdict(compliant, 'V-220651')
    check('V-220651 passes on the shape the Check Content shows',
          status(compliant, 'V-220651') == 'PASS', line)
    check('and the reason names the traffic types it found bandwidth reserved for',
          all(t in line for t in ('C2_VOICE', 'VOICE', 'VIDEO', 'PREFERRED_DATA')), line)

    none = report_for(tmpdir, 'noqos',
                      running_config=strip_service_policy(fixtures.RUNNING_CONFIG))
    line = verdict(none, 'V-220651')
    check('no service-policy anywhere is "QoS is not enabled"',
          status(none, 'V-220651') == 'FAIL' and 'not enabled' in line, line)

    partial = report_for(tmpdir, 'partialqos', running_config=strip_service_policy(
        fixtures.RUNNING_CONFIG, 'GigabitEthernet1/0/1'))
    line = verdict(partial, 'V-220651')
    check('a port left out of the policy is a finding',
          status(partial, 'V-220651') == 'FAIL', line)
    check('and the port is named, like every other per-port rule here',
          'GigabitEthernet1/0/1' in line, line)

    renamed = fixtures.RUNNING_CONFIG
    for stig_name, local in (('C2_VOICE', 'SITE-C2'), ('VOICE', 'SITE-VOICE'),
                             ('VIDEO', 'SITE-VIDEO'), ('PREFERRED_DATA', 'SITE-DATA')):
        renamed = re.sub(rf'\b{stig_name}\b', local, renamed)
    local_names = report_for(tmpdir, 'renamedqos', running_config=renamed)
    line = verdict(local_names, 'V-220651')
    check('the same policy under local class names still passes - DSCP decides, not spelling',
          status(local_names, 'V-220651') == 'PASS', line)

    marking_only = re.sub(r'^  (priority level \d+ \d+|bandwidth percent \d+)$',
                          '  set dscp af11', fixtures.RUNNING_CONFIG, flags=re.M)
    line = verdict(report_for(tmpdir, 'markingonly', running_config=marking_only), 'V-220651')
    check('a policy that only marks traffic reserves nothing, so it is a finding',
          'FAIL' in line and 'reserves bandwidth' in line, line)


if __name__ == '__main__':
    with tempfile.TemporaryDirectory() as tmp:
        test_persistent_logging(tmp)
        test_pki_trustpoint(tmp)
        test_supported_release(tmp)
        test_qos_bandwidth(tmp)
    print('\n' + ('ALL CHECKS PASSED' if not failures
                  else f'{len(failures)} FAILED: {", ".join(failures)}'))
    sys.exit(1 if failures else 0)
